### ISSUE TITLE
Mnemonic phrase should BIP39 compliant (generate a real checksum)

### ISSUE THREAD

**Issue by kellybyrd** [helium/helium-js#188]
The current mobile wallet generates a 12-word mnemonic phrase that always has a `0000` checksum. This isn't BIP39 compliant. I noticed this while adding support for real BIP39 phrases into helium-wallet-rs. As the Helium ecosystem gets bigger, and we include things like ledger wallet I can see this being more and more of an issue. IMO, it is reasonable to expect a mnemonic phrase for a crypto wallet to be BIP39 compliant. 

Right now, the CLI wallet supports importing both mobile and CLI, and I have a PR for exporting a mnemonic phrase for an existing wallet. Both of these code paths, have to support "mobile" and "bip39" checksums in order to not surprise users.

Having to support two paths seems like a bad way forward. But, we have to be careful about the upgrade path. A suggestion from Discord:

* Fix this library (and then update the mobile wallet) so it always output only a BIP39-compliant  mnemonic phrase, rather than a phrase with a `0000` checksum.
* It has to be backwards compatible, so that users of "old mobile wallets" can still import their phrases. I don't think notifying users and expecting all will "update" their offline copy of their phrase is good enough. So, on import, the mobile wallet (using this library) should converting both mobile and BIP39 phrases into entropy. 

Then eventually maybe the CLI wallet can drop support for importing mobile phrases and only import BIP39 phrases. Or at the very least, the CLI wallet will not output mobile-type phrases on output (there's a PR on helium-wallet-rs to optionally output phrases in the verify subcommand)

One note, I'm not 100% sure, but AFAICT, a given secret can output both a mobile-type and BIP39 type phrase. Re-importing either into the mobile wallet will result in the same secret, which results in the same wallet and same public address. To put it another way, the mnemonic phrase checksum isn't part of the entropy stored that makes up the keypair. So changing just the checksum calculation and using that when showing the phrase to the user should not (again AFAICT) change the actual keypair that gets derived from that phrase on import. 

To make this more transparent to the mobile app user the `entropyFromMnemonic()` path  could just do (pseudocode)
```
If foundChecksum ==  '0000' or foundChecksum == bip39CalcChecksum:
   create entropy from this phrase.
```
This weakens the bip39 checksum verification a bit, but...maybe doesn't matter?

Note: I commented on #120 because I thought it was about this issue. But I don't think it is.

**Comment by vulet** [comment]
It looks like Bob in #120 has created their own passphrase by going down the word list alphabetically, so Bob's passphrase will still fail.

**Comment by kellybyrd** [comment]
> It looks like Bob in #120 has created their own passphrase by going down the word list alphabetically, so Bob's passphrase will still fail.

I don't understand your point. Generating a passphrase by just going down the wordlist and choosing words doesn't lead to a valid BIP39 phrase. You can choose almost all the words, but for the last word, you have to use the checksum algorithm to help you choose that last word. Depending on 12 vs 24 word phrase, the bits represented by the checksum may be one entire word, or just the LSB of the value that selects the word.

**Comment by vulet** [comment]
> Generating a passphrase by just going down the wordlist and choosing words doesn't lead to a valid BIP39 phrase. 

That is exactly what I mean @kellybyrd, check out OP on the issue.

**Comment by tyler-whitman** [comment]
This was fixed by https://github.com/helium/helium-js/pull/267
