### ISSUE TITLE
[@helium/transactions] Setting unsigned PaymentV2.toString() and then recreating with .fromString() creates a bad signatures when memo isn't present

### ISSUE THREAD

**Issue by syuan100** [helium/helium-js#190]
I'm currently working on an implementation that takes unsigned transactions, signs them in an offline environment, and then takes the signed txn and submits it online again.

I've been running into an inexplicable issue where the PaymentV2 transaction behaves strangely when the unsigned transaction is serialized + encoded in base64, and then decoded and unserialized. Short example below where keypair is a `Keypair` derived from words:

```
const brokenTxn: PaymentV2 = PaymentV2.fromString(unsignedPaymentV2Txn.toString());
const signedBrokenTxn: PaymentV2 = await brokenTxn.sign({payer: keypair});
const pendingBrokenTxn: PendingTransaction = await client.transactions.submit(signedBrokenTxn.toString());
```

Eventually, the `pendingBrokenTxn` will fail with the failure reason of `{invalid,bad_signature}`.

To be clear, this only happens in two cases: 
- If the memo field is undefined
- If the memo field is preemptively filled with the string "AAAAAAAAAAA=" 

When the memo field is populated, the signed transaction will clear (based on my testing so far).

**Comment by ke6jjj** [comment]
This sounds eerily related to issue #144.
