### ISSUE TITLE
Private Key size invalid

### ISSUE THREAD

**Issue by sawyerru** [helium/helium-js#241]
Hello, I'm working on a project that needs to generate keys, then sign a message and verify a message. The function signatures are below:

`{publicKey, privateKey} keygen()`
`string signMessage(string message, string privateKey)`
`bool verifyMessage(string message, string signature, string publicKey)`

When I use @helium/crypto to generate the key pair I get the privateKey.length = 64, and publicKey.length = 32. However, when I try to recreate the keypair object using FromEntropy, I would expect to pass the private key, but I need to pass a 32 byte string array. 

Where is this seed generated? Is there a missing method to collect this or some other way to derive the seed from the private key? Thanks!

**Comment by allenan** [comment]
hey @sawyerru. You can see how `fromEntropy` is used in this test case:

https://github.com/helium/helium-js/blob/master/packages/crypto/src/__tests__/Keypair.spec.ts#L49

Its intended use case is, given 32 bytes of entropy, that entropy can be stored in a database and used to recreate a keypair.

You can generate the entropy any way you like, but we include a utility method that uses the same libsodium library to generate those bytes and format them correctly:

```js
import { Keypair, utils } from '@helium/crypto'

const keypairEntropy = await utils.randomBytes(32)
const keypair = await Keypair.fromEntropy(keypairEntropy)
```

This feature is probably under documented, but always happy to accept documentation PRs :)
