### ISSUE TITLE
PaymentV1 Error : (invalid,bad_signature)

### ISSUE THREAD

**Issue by DeLaColinaSalvador** [helium/helium-js#307]
Hello, we’re trying to make a PaymentV1 transaction  as described on readme.md. We’re using the latest versión of the repository, we generate the signed payment and submit it, but when looking at the helium api response for the transaction(https://api.helium.io/v1/pending_transactions/xrHd9AIx9Jd3l_TZzvGAc8wKYg9dUjtzrhYkChK8g9s) 
this is what we get:
   "status": "failed",
   "failed_reason": "{invalid,bad_signature}",
   
   This are the imports
```
   import * as crypto from '@helium/crypto';
   import * as transactions from '@helium/transactions';
   import * as http from '@helium/http';
   import Address from '@helium/address';
```

   The req body is 
   
   ```
{ keypair : ['one','two','three','four',...,'twelve']
     ,payeeAdress : a b58 string
     ,amount: a number, in this case 0.00001
      }
   
```

   The client and vars are initialized and set correctly
   
```  
    const client = new http.Client();
    const vars = await client.vars.get();
    transactions.Transaction.config(vars);
```
We also initialize the payer account and address and also the payee address

```
    const payer = await crypto.Keypair.fromWords(keypair);
    const payee = Address.fromB58(payeeAdress);
    const account = await client.accounts.get(payer.address.b58);
```

We build the payment txn

```
    const paymentTxn = new transactions.PaymentV1({
      payer: payer.address,
      payee: payee,
      amount: amount,
      nonce: account.speculativeNonce! + 1,
    });
```

We sign it and submit it to the Blockchain API

`const signedPaymentTxn = await  paymentTxn.sign({payer : payer}) `

[...] (then…)
`client.transactions.submit(signedPaymentTxn.toString())`

(and print the request before send…)
` console.log(signedPaymentTxn);`

PaymentV1 {
>    type: 'payment_v1',
>    payer: Address {
>      version: 0,
>      netType: 0,
>      keyType: 1,
>      publicKey: Uint8Array(32) [
>        221,  47,  **, ***, ***, ***, **, ***,
>        ***, ***, ***, ***,  **,  **, **,  **,
>        ***,  **,  **,  **, ***, ***, **, ***,
>          *, ***, ***,  **, ***, ***, **,  **
>      ]
>    },
>    payee: Address {
>      version: 0,
>      netType: 0,
>      keyType: 1,
>      publicKey: <Buffer ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** ** **>
>    },
>    amount: 0.0001,
>    nonce: 5,
>    fee: 30000,
>    signature: Uint8Array(64) [
>      ***, ***, ***, ***,  **, ***,  **, ***,  **, ***, ***,
>       ***, ***, ***, ***,  ***,  ***, ***,  ***,  ***,  **, ***,
>       **, ***,  ***,  ***, ***, ***, ***, ***, ***, ***, ***,
>      ***,  **, ***,  **, ***, ***, ***,  ***, ***, ***, ***,
>      ***,  **, ***, ***, ***, ***, ***, ***, ***,   *, ***,
>       **, ***, ***, ***,   *, ***, ***,  **,   *
>    ]
>  }
Also I will mentionate that we’re sending 0.0001 HNT, and in the response json object it shows 
   "amount": 0
Anyway, probably the amount is 0 because of the bad_signature error.

**Comment by tyler-whitman** [comment]
Thanks for the detailed report, a `bad_signature` error can happen when the format of the transaction is incorrect. I believe the problem here is the amount. If you are trying to send `0.0001` HNT this should be added to a PaymentV1 transaction in bones not as a float amount. HNT supports 8 decimal places so we need to multiply float amounts by 100000000. There is a convenient class [Balance](https://helium.github.io/helium-js/classes/currency.Balance.html) to do the calculations for you. You can use `Balance.fromFloat(0.00001, CurrencyType.networkToken).integerBalance` to make sure the value is correct. Accessing the `floatBalance` from that would return back the `0.00001`.

**Comment by DeLaColinaSalvador** [comment]
Yes, that solved the issue.

Thank you for answering and i'll take your suggestion and move to `PaymentV2`
